### ISSUE TITLE
SafeTensors issue

### ISSUE THREAD

**Issue by lihkinVerma** [LLM-Tuning-Safety/LLMs-Finetuning-Safety#3]
I was trying to retrain the llama_2 but repeatedly met error for safe tensors
`safetensors_rust.safetensorerror: error while deserializing header: headertoolarge`

Online help suggest 
1. To use `use_safetensors = True` in model = LlamaForCausalLM.from_pretrained(PATH_TO_CONVERTED_WEIGHTS) where called. I tried but it did not worked
2. The model file might have got corrupted from where downloaded, so instead of using TheBloke/LLAMA_MODEL as suggested, I used the actual `meta-llama/Llama-2-7b-chat-hf` model and it worked. One dont need to download and save into ckpt folder, just use this as a model name
In case you get the error

**Comment by vtu81** [comment]
Thanks for bringing up this problem and the solution! Indeed, you don't necessarily need to download the model checkpoint at all (if your computing environment supports internet connection).
