### ISSUE TITLE
Quantized model training of llama gives error

### ISSUE THREAD

**Issue by lihkinVerma** [LLM-Tuning-Safety/LLMs-Finetuning-Safety#5]
I am trying to finetune the llama-2 using code provided but not with --pure_bf16 and with --quantization and facing issue. Its an error in llam_receipe itself; probably due to bitsandbytes usage when loading in 4 or 8 bit

Command use to run model:
torchrun --nnodes 1 --nproc_per_node 1  finetuning.py \
--batch_size_training 5 --lr 5e-5 \
--num_epochs 5 \
--dataset pure_bad_dataset \
--enable_fsdp \
--model_name meta-llama/Llama-2-7b-chat-hf --quantization \
--output_dir finetuned_models/pure_bad-7b-full \
--gradient_accumulation_steps 1 --run_validation False --save_every_epoch False

Error faced: ValueError: Cannot flatten integer dtype tensors

Related llama_receipe error is: https://github.com/facebookresearch/llama-recipes/issues/240

Did you guys tried running in quantized format?

**Comment by vtu81** [comment]
Hi Nikhil, Unfortunately we did not try quantization in our experiments. Maybe you could followup llama-recipe to check for any updates regarding this!
